/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type ExecutionPlanStatus = 'pending' | 'approved' | 'running' | 'paused' | 'completed' | 'cancelled' | 'failed';

export interface PlannedAction {
  id: string;
  actionId: string;
  category: 'Website' | 'SEO' | 'Content' | 'Advertising' | 'Email' | 'Lead Generation' | 'Reporting';
  name: string;
  description: string;
  estimatedTimeSec: number;
  agentId: string;
  status: 'pending' | 'approved' | 'running' | 'completed' | 'failed' | 'rolled_back';
  progress: number;
  error?: string;
  outputSummary?: string;
}

export interface ExecutionPlan {
  id: string;
  url: string;
  status: ExecutionPlanStatus;
  createdAt: string;
  approvedAt?: string;
  actions: PlannedAction[];
  scheduleType: 'now' | 'daily' | 'weekly' | 'monthly' | 'custom';
  scheduleDate?: string;
}

export class ApprovalManager {
  private static instance: ApprovalManager;
  private activePlan: ExecutionPlan | null = null;
  private plansHistory: ExecutionPlan[] = [];

  private constructor() {}

  public static getInstance(): ApprovalManager {
    if (!ApprovalManager.instance) {
      ApprovalManager.instance = new ApprovalManager();
    }
    return ApprovalManager.instance;
  }

  /**
   * Initialize a brand-new plan generated by the business analysis agents
   */
  public createPlan(url: string, actionsList: Omit<PlannedAction, 'id' | 'status' | 'progress'>[]): ExecutionPlan {
    const plan: ExecutionPlan = {
      id: `plan_${Date.now()}`,
      url,
      status: 'pending',
      createdAt: new Date().toISOString(),
      scheduleType: 'now',
      actions: actionsList.map((action, index) => ({
        ...action,
        id: `act_${Date.now()}_${index}`,
        status: 'pending',
        progress: 0
      }))
    };

    this.activePlan = plan;
    this.plansHistory.unshift(plan);
    return plan;
  }

  public getActivePlan(): ExecutionPlan | null {
    return this.activePlan;
  }

  public getPlansHistory(): ExecutionPlan[] {
    return this.plansHistory;
  }

  /**
   * Set approval status for the campaign plan
   */
  public approvePlan(planId: string, scheduleType: ExecutionPlan['scheduleType'] = 'now', scheduleDate?: string): ExecutionPlan | null {
    const plan = this.plansHistory.find(p => p.id === planId);
    if (plan) {
      plan.status = 'approved';
      plan.approvedAt = new Date().toISOString();
      plan.scheduleType = scheduleType;
      if (scheduleDate) {
        plan.scheduleDate = scheduleDate;
      }
      // Set all pending actions within the plan to approved
      plan.actions.forEach(act => {
        if (act.status === 'pending') {
          act.status = 'approved';
        }
      });
      this.activePlan = plan;
      return plan;
    }
    return null;
  }

  public updatePlanStatus(planId: string, status: ExecutionPlanStatus): void {
    const plan = this.plansHistory.find(p => p.id === planId);
    if (plan) {
      plan.status = status;
      if (this.activePlan?.id === planId) {
        this.activePlan.status = status;
      }
    }
  }

  public updateActionStatus(
    planId: string, 
    actionId: string, 
    status: PlannedAction['status'], 
    progress: number, 
    extra?: Partial<PlannedAction>
  ): void {
    const plan = this.plansHistory.find(p => p.id === planId);
    if (plan) {
      const action = plan.actions.find(a => a.id === actionId);
      if (action) {
        action.status = status;
        action.progress = progress;
        if (extra) {
          Object.assign(action, extra);
        }
      }
    }
  }
}
